# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubi',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
